# Generated by Django 4.0.6 on 2022-08-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
